// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATVjrfDqUlrUmpS1uQUPUBNC5eCLO5D6U',
    appId: '1:444875794216:android:0cf772ffb7fae38439d21d',
    messagingSenderId: '444875794216',
    projectId: 'videosdk-codesample-analytics',
    storageBucket: 'videosdk-codesample-analytics.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUsvi-vZtgTeK9fWqJIhqTLw80Vo_8diw',
    appId: '1:107235112902:ios:1bb5a20bec255b1b1ea4c7',
    messagingSenderId: '444875794216',
    projectId: 'videosdk-codesample-analytics',
    storageBucket: 'videosdk-codesample-analytics.appspot.com',
    iosClientId:
        '107235112902-3fk42mqa01dlk08qmj13j4d9k0c69evo.apps.googleusercontent.com',
    iosBundleId: 'com.app.loginfo',
  );
}
